version '0.0'

services:

  app:
    # add Java JDK
    image: openjdk:23-jdk-slim
    ports:
      - 8088:8088
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DB: test_db
      
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./db/rabbitmq/data/:/var/lib/rabbitmq/
        - ./db/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net
    db:
        image: mysql:8.0
        environment:
        
    networks:
      rabbitmq_go_net:
        driver: bridge
    
    environment:
        MYSQL_ROOT_PASSWORD: root
    volumes:
        - db-data:/var/lib/mysql
        - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
        - app-network
